import "./AIArts.css";
import React from "react";
import Carousel from "./Carousel";

const images = [
  "src/assets/AI-art-1.jpg",
  "src/assets/AI-art-2.jpg",
  "src/assets/AI-art-3.jpg",
];

function AIArts() {
  return (
    <div className="carousel-container">
      <Carousel images={images} />
      <p className="artwork-content">
        The emergence of AI-image generators, such as DALL-E 2, Discord,
        Midjourney, and others, has stirred a controversy over whether art
        generated by artificial intelligence should be considered real art — and
        whether it could put artists and creators out of work.
      </p>
      <p className="artwork-content">
        <b>
          AI artwork is the way designer and artist get their inspiration from.{" "}
        </b>
      </p>
      <p className="artwork-content">
        Using AI can make the design process faster and easier by automating
        mundane tasks that would otherwise eat up valuable time and resources.
        Giving designers more time to focus on the creative aspects of the
        design process, such as conceptualizing and refining ideas. Building
        wireframes, organizing page element layouts, image enhancement,
        adjusting typography – there’s an AI out there for all of it.
      </p>
    </div>
  );
}

export default AIArts;
